export const dataList = [
    "grades",
    "homeworks",
    "upcomingAssignments",
    "schoolLife",
    "messageFolders",
    "messages",
    "activePeriod",
    "administrativeDocuments",
    "totalBadges",
    "generalAverageHistory",
    "classGeneralAverageHistory",
    "streakScoreHistory",
    "subjectsComparativeInformation",
    "gradesEnabledFeatures",
    "lastGrades",
]